config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :parts
  resources :orders
  resources :order_details
  resources :employees
  resources :customers

end

app/models/part.rb
class Part < ActiveRecord::Base
	self.table_name = "Parts"
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:PNAME, :PRICE, :QUANTITY)
    end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= form_for(@part) do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% @part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :PNAME %><br>
    <%= f.text_field :PNAME %>
  </div>
  <div class="field">
    <%= f.label :PRICE %><br>
    <%= f.number_field :PRICE %>
  </div>
  <div class="field">
    <%= f.label :QUANTITY %><br>
    <%= f.number_field :QUANTITY %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form' %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parts</h1>

<table>
  <thead>
    <tr>
      <th>Pname</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.PNAME %></td>
        <td><%= part.PRICE %></td>
        <td><%= part.QUANTITY %></td>
        <td><%= link_to 'Show', part %></td>
        <td><%= link_to 'Edit', edit_part_path(part) %></td>
        <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Part', new_part_path %>

app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form' %>

<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pname:</strong>
  <%= @part.PNAME %>
</p>

<p>
  <strong>Price:</strong>
  <%= @part.PRICE %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @part.QUANTITY %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>