config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :parts
  resources :orders
  resources :order_details
  resources :employees
  resources :customers

end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
	self.table_name = "Order_Details"
	self.primary_keys = :ONO,:PNO
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
  before_action :set_order_detail, only: [:show, :edit, :update, :destroy]

  # GET /order_details
  # GET /order_details.json
  def index
    @order_details = OrderDetail.all
  end

  # GET /order_details/1
  # GET /order_details/1.json
  def show
  end

  # GET /order_details/new
  def new
    @order_detail = OrderDetail.new
  end

  # GET /order_details/1/edit
  def edit
  end

  # POST /order_details
  # POST /order_details.json
  def create
    @order_detail = OrderDetail.new(order_detail_params)

    respond_to do |format|
      if @order_detail.save
        format.html { redirect_to @order_detail, notice: 'Order detail was successfully created.' }
        format.json { render :show, status: :created, location: @order_detail }
      else
        format.html { render :new }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_details/1
  # PATCH/PUT /order_details/1.json
  def update
    respond_to do |format|
      if @order_detail.update(order_detail_params)
        format.html { redirect_to @order_detail, notice: 'Order detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_detail }
      else
        format.html { render :edit }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_details/1
  # DELETE /order_details/1.json
  def destroy
    @order_detail.destroy
    respond_to do |format|
      format.html { redirect_to order_details_url, notice: 'Order detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_detail
      @order_detail = OrderDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_detail_params
      params.require(:order_detail).permit(:ONO, :PNO, :QUANTITY)
    end
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/order_details/_form.html.erb
<%= form_for(@order_detail) do |f| %>
  <% if @order_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_detail.errors.count, "error") %> prohibited this order_detail from being saved:</h2>

      <ul>
      <% @order_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ONO %><br>
    <%= f.number_field :ONO %>
  </div>
  <div class="field">
    <%= f.label :PNO %><br>
    <%= f.number_field :PNO %>
  </div>
  <div class="field">
    <%= f.label :QUANTITY %><br>
    <%= f.number_field :QUANTITY %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_details/edit.html.erb
<h1>Editing Order Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_detail %> |
<%= link_to 'Back', order_details_path %>

app/views/order_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Order Details</h1>

<table>
  <thead>
    <tr>
      <th>Ono</th>
      <th>Pno</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_details.each do |order_detail| %>
      <tr>
        <td><%= order_detail.ONO %></td>
        <td><%= order_detail.PNO %></td>
        <td><%= order_detail.QUANTITY %></td>
        <td><%= link_to 'Show', order_detail %></td>
        <td><%= link_to 'Edit', edit_order_detail_path(order_detail) %></td>
        <td><%= link_to 'Destroy', order_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order detail', new_order_detail_path %>

app/views/order_details/new.html.erb
<h1>New Order Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', order_details_path %>

app/views/order_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ono:</strong>
  <%= @order_detail.ONO %>
</p>

<p>
  <strong>Pno:</strong>
  <%= @order_detail.PNO %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_detail.QUANTITY %>
</p>

<%= link_to 'Edit', edit_order_detail_path(@order_detail) %> |
<%= link_to 'Back', order_details_path %>